/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConsolaVideojuego;
import modelo.Videojuego;
import controlador.VideojuegoController;
import java.util.List;
import javax.swing.JFrame;
import modelo.EstadoVideojuego;
import util.EstilosUI;

/**
 *
 * @author usr
 */
public class VentanaVideojuegos extends javax.swing.JFrame {

    private VideojuegoController controlador;
    private Videojuego videojuegoSeleccionado;

    /**
     * Creates new form VentanaVideojuegos
     */
    public VentanaVideojuegos() {
        initComponents();
        controlador = new VideojuegoController();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cargarConsolas();
        cargarTabla();

        aplicarEstilos();

        setLocationRelativeTo(null);
        pack();
    }

    private void aplicarEstilos() {

        getContentPane().setBackground(
                EstilosUI.FONDO
        );

        EstilosUI.estilizarCampo(
                txtNombre
        );

        EstilosUI.estilizarCombo(
                cmbConsola
        );

        EstilosUI.estilizarBoton(
                btnGuardar
        );

        EstilosUI.estilizarBoton(
                btnActualizar
        );

        EstilosUI.estilizarBotonPeligro(
                btnEliminar
        );

        EstilosUI.estilizarTabla(
                tblVideojuegos
        );

        lblNombre.setForeground(
                EstilosUI.TEXTO
        );

        lblConsola.setForeground(
                EstilosUI.TEXTO
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblConsola = new javax.swing.JLabel();
        cmbConsola = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVideojuegos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Videojuegos");
        setResizable(false);

        lblNombre.setText("Nombre:");

        lblConsola.setText("Consola: ");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tblVideojuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CONSOLA", "DISPONIBILIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVideojuegos.setCellSelectionEnabled(true);
        tblVideojuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVideojuegosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVideojuegos);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGuardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNombre)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnActualizar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblConsola)
                            .addGap(18, 18, 18)
                            .addComponent(cmbConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsola))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarConsolas() {
        cmbConsola.removeAllItems();
        for (ConsolaVideojuego consola : ConsolaVideojuego.values()) {
            cmbConsola.addItem(consola);
        }
    }

    private void cargarTabla() {
        DefaultTableModel modeloTabla
                = (DefaultTableModel) tblVideojuegos.getModel();

        modeloTabla.setRowCount(0);

        List<Videojuego> videojuegos = controlador.obtener();

        for (Videojuego videojuego : videojuegos) {

            Object[] fila = {
                videojuego.getId(),
                videojuego.getNombre(),
                videojuego.getConsola(),
                videojuego.getDisponibilidad()
            };

            modeloTabla.addRow(fila);
        }

    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        ConsolaVideojuego consola = (ConsolaVideojuego) cmbConsola.getSelectedItem();
        Videojuego videojuego = new Videojuego(nombre, consola);
        String mensaje = controlador.guardar(videojuego);
        JOptionPane.showMessageDialog(this, mensaje);
        cargarTabla();
        txtNombre.setText("");
        cmbConsola.setSelectedIndex(0);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblVideojuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVideojuegosMouseClicked
        int filaSeleccionada
                = tblVideojuegos.getSelectedRow();

        if (filaSeleccionada >= 0) {

            int id
                    = Integer.parseInt(
                            tblVideojuegos
                                    .getValueAt(filaSeleccionada, 0)
                                    .toString()
                    );

            String nombre
                    = tblVideojuegos
                            .getValueAt(filaSeleccionada, 1)
                            .toString();

            ConsolaVideojuego consola
                    = ConsolaVideojuego.valueOf(
                            tblVideojuegos.getValueAt(filaSeleccionada, 2)
                                    .toString()
                    );

            EstadoVideojuego estado
                    = EstadoVideojuego.valueOf(
                            tblVideojuegos.getValueAt(filaSeleccionada, 3)
                                    .toString()
                    );

            videojuegoSeleccionado = new Videojuego(id, nombre, consola, estado);

            txtNombre.setText(nombre);
            cmbConsola.setSelectedItem(consola);
        }
    }//GEN-LAST:event_tblVideojuegosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

        if (videojuegoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un videojuego");
            return;
        }

        String nombre = txtNombre.getText().trim();
        ConsolaVideojuego consola = (ConsolaVideojuego) cmbConsola.getSelectedItem();

        Videojuego videojuegoActualizado = new Videojuego(
                videojuegoSeleccionado.getId(),
                nombre,
                consola,
                videojuegoSeleccionado.getDisponibilidad()
        );

        String mensaje = controlador.actualizar(videojuegoActualizado);

        JOptionPane.showMessageDialog(this, mensaje);
        cargarTabla();

        videojuegoSeleccionado = null;
        txtNombre.setText("");
        cmbConsola.setSelectedIndex(0);
        tblVideojuegos.clearSelection();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (videojuegoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun videojuego");
            return;
        }

        int confirmacion
                = JOptionPane.showConfirmDialog(this, "Desea Eliminar el juego " + videojuegoSeleccionado.getId() + ": " + videojuegoSeleccionado.getNombre(), "Eliminar", JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Cancelado");
            return;
        }

        String mensaje = controlador.eliminar(videojuegoSeleccionado);

        JOptionPane.showMessageDialog(this, mensaje);
        cargarTabla();

        videojuegoSeleccionado = null;
        txtNombre.setText("");
        cmbConsola.setSelectedIndex(0);
        tblVideojuegos.clearSelection();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<ConsolaVideojuego> cmbConsola;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsola;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblVideojuegos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
