/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import modelo.Prestamo;
import vista.VentanaCliente;
import vista.VentanaVideojuegos;

/**
 *
 * @author usr
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
        
        cargarImagenMenu();
        aplicarEstilos();
        pack();
        setLocationRelativeTo(null);
    }

    private void cargarImagenMenu() {
        ImageIcon icono = new ImageIcon(
                getClass().getResource(
                        "/recursos/imagenes/menu.png"
                )
        );

        Image imagen = icono.getImage().getScaledInstance(
                60,
                120,
                Image.SCALE_SMOOTH
        );

        lblImagenMenu.setIcon(new ImageIcon(imagen));
    }

    private void aplicarEstilos() {

        getContentPane().setBackground(
                util.EstilosUI.FONDO
        );

        util.EstilosUI.estilizarBoton(
                btnVideojuego
        );

        util.EstilosUI.estilizarBoton(
                btnClientes
        );

        util.EstilosUI.estilizarBoton(
                btnPrestamos
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloSelecciona = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        btnVideojuego = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        lblImagenMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloSelecciona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloSelecciona.setText("Que quieres hacer?");

        lblMenu.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblMenu.setText("MENU");

        btnVideojuego.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVideojuego.setText("Videojuegos");
        btnVideojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVideojuegoActionPerformed(evt);
            }
        });

        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnPrestamos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrestamos.setText("Prestamos");
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVideojuego)
                            .addComponent(lblTituloSelecciona)
                            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblMenu)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImagenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloSelecciona, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVideojuego)
                .addGap(18, 18, 18)
                .addComponent(btnClientes)
                .addGap(18, 18, 18)
                .addComponent(btnPrestamos)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVideojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVideojuegoActionPerformed
        // TODO add your handling code here:
        VentanaVideojuegos videojuegos = new VentanaVideojuegos();
        videojuegos.setVisible(true);
    }//GEN-LAST:event_btnVideojuegoActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        VentanaCliente clientes = new VentanaCliente();
        clientes.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        // TODO add your handling code here:
        VentanaPrestamo prestamo = new VentanaPrestamo();
        prestamo.setVisible(true);
    }//GEN-LAST:event_btnPrestamosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnVideojuego;
    private javax.swing.JLabel lblImagenMenu;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblTituloSelecciona;
    // End of variables declaration//GEN-END:variables
}
