/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

import modelo.Cliente;
import modelo.EstadoVideojuego;
import modelo.Videojuego;
import modelo.Prestamo;

import controlador.PrestamoController;
import controlador.ClienteController;
import controlador.VideojuegoController;

/**
 *
 * @author usr
 */
public class VentanaPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrestamo
     */
    private VideojuegoController videojuegoControlador;
    private ClienteController clienteControlador;
    private PrestamoController prestamoControlador;

    private Prestamo prestamoSeleccionado;

    private List<Prestamo> prestamos;

    public VentanaPrestamo() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        videojuegoControlador = new VideojuegoController();
        clienteControlador = new ClienteController();
        prestamoControlador = new PrestamoController();

        cargarClietes();
        cargarVideojuegos();
        cargarPrestamos();

        aplicarEstilos();
        
        pack();
        setLocationRelativeTo(null);
    }

    private void aplicarEstilos() {

        getContentPane().setBackground(
                util.EstilosUI.FONDO
        );

        util.EstilosUI.estilizarCombo(
                cmbCliente
        );

        util.EstilosUI.estilizarCombo(
                cmbVideojuego
        );

        util.EstilosUI.estilizarCampo(
                txtFcehaPrestamo
        );

        util.EstilosUI.estilizarCampo(
                txtFechaDevolucion
        );

        util.EstilosUI.estilizarBoton(
                btnPrestar
        );

        util.EstilosUI.estilizarBoton(
                btnEntregado
        );

        util.EstilosUI.estilizarTabla(
                tblPrestamos
        );
    }

    private void cargarClietes() {
        cmbCliente.removeAllItems();
        List<Cliente> clientes = clienteControlador.obtener();

        for (Cliente cliente : clientes) {
            cmbCliente.addItem(cliente);
        }
    }

    private void cargarVideojuegos() {
        cmbVideojuego.removeAllItems();

        List<Videojuego> videojuegos = videojuegoControlador.obtener();

        for (Videojuego videojuego : videojuegos) {
            if (videojuego.estaDisponible()) {
                cmbVideojuego.addItem(videojuego);
            }
        }
    }

    private void cargarPrestamos() {
        DefaultTableModel tablaPrestamoModelo
                = (DefaultTableModel) tblPrestamos.getModel();

        tablaPrestamoModelo.setRowCount(0);

        prestamos = prestamoControlador.obtner();

        for (Prestamo prestamo : prestamos) {

            Object[] filaPrestamos = {
                prestamo.getId(),
                prestamo.getCliente(),
                prestamo.getVideojuego(),
                prestamo.getFechaPrestamo(),
                prestamo.getFechaDevolucion()
            };

            tablaPrestamoModelo.addRow(filaPrestamos);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCliente = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        lblVideojuego = new javax.swing.JLabel();
        cmbVideojuego = new javax.swing.JComboBox<>();
        lblFechaPrestamo = new javax.swing.JLabel();
        txtFcehaPrestamo = new javax.swing.JTextField();
        lblFechaDevolucion = new javax.swing.JLabel();
        txtFechaDevolucion = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        btnEntregado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de prestamos");

        lblCliente.setText("Cliente: ");

        lblVideojuego.setText("Videouego:");

        lblFechaPrestamo.setText("Fecha Prestamo: ");

        lblFechaDevolucion.setText("Fecha devolucion: ");

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "CLIENTE", "VIDEOJUEGO", "FECHA PRESTAMO", "FECHA DEVOLUCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrestamos);

        btnEntregado.setText("Marcar Entregado");
        btnEntregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaDevolucion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFechaPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblVideojuego))
                                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFcehaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(91, 91, 91))
                                    .addComponent(cmbVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(122, 122, 122))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPrestar)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEntregado)
                        .addGap(226, 226, 226))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFcehaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaDevolucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrestar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntregado)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        // TODO add your handling code here:
        try {
            Cliente cliente = (Cliente) cmbCliente.getSelectedItem();

            Videojuego videojuego = (Videojuego) cmbVideojuego.getSelectedItem();

            LocalDate fechaPrestamo = LocalDate.parse(txtFcehaPrestamo.getText().trim());

            LocalDate fechaDevolucion = LocalDate.parse(txtFechaDevolucion.getText().trim());

            Prestamo prestamo = new Prestamo(
                    cliente,
                    videojuego,
                    fechaPrestamo,
                    fechaDevolucion
            );

            String mensaje = prestamoControlador.guardar(prestamo);
            JOptionPane.showMessageDialog(this, mensaje);

            cargarVideojuegos();
            cargarPrestamos();

            cmbCliente.setSelectedIndex(0);
            cmbVideojuego.setSelectedIndex(0);

            txtFcehaPrestamo.setText("");
            txtFechaDevolucion.setText("");

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "LA FECHA DEBE DE TENER EL FORMATO AAAA-MM-DD");
        }
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnEntregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregadoActionPerformed
        // TODO add your handling code here:
        if (prestamoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "NO se ha seleccionado ningun prestamo");
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(this,
                "Prestamo: " + prestamoSeleccionado.getId() + " - " + prestamoSeleccionado.getFechaPrestamo() + " \n"
                + prestamoSeleccionado.getCliente() + " \n" + prestamoSeleccionado.getVideojuego(),
                "Marcar como entregado", JOptionPane.YES_NO_OPTION);

        if (confirmar != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Cancelado");
            return;
        }

        String mensaje = prestamoControlador.entregar(prestamoSeleccionado);

        JOptionPane.showMessageDialog(this, mensaje);

        prestamoSeleccionado = null;
        cargarPrestamos();
        cargarVideojuegos();
        tblPrestamos.clearSelection();
    }//GEN-LAST:event_btnEntregadoActionPerformed

    private void tblPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestamosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada
                = tblPrestamos.getSelectedRow();

        if (filaSeleccionada >= 0) {

            int id
                    = Integer.parseInt(tblPrestamos.getValueAt(filaSeleccionada, 0).toString());

            Cliente cliente
                    = (Cliente) tblPrestamos.getValueAt(filaSeleccionada, 1);

            Videojuego videojuego
                    = (Videojuego) tblPrestamos.getValueAt(filaSeleccionada, 2);

            LocalDate fechaPrestamo
                    = LocalDate.parse(tblPrestamos.getValueAt(filaSeleccionada, 3).toString());

            LocalDate fechaDevolucion
                    = LocalDate.parse(tblPrestamos.getValueAt(filaSeleccionada, 4).toString());

            boolean entregado = false;

            prestamoSeleccionado = new Prestamo(
                    id,
                    cliente,
                    videojuego,
                    fechaPrestamo,
                    fechaDevolucion,
                    entregado
            );
        }
    }//GEN-LAST:event_tblPrestamosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregado;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JComboBox<Cliente> cmbCliente;
    private javax.swing.JComboBox<Videojuego> cmbVideojuego;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFechaDevolucion;
    private javax.swing.JLabel lblFechaPrestamo;
    private javax.swing.JLabel lblVideojuego;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTextField txtFcehaPrestamo;
    private javax.swing.JTextField txtFechaDevolucion;
    // End of variables declaration//GEN-END:variables
}
